@startuml

title __APP's Class Diagram__\n

  package com.raywenderlich.android.imet {
    class BuildConfig {
    }
  }
  

  package com.raywenderlich.android.imet {
    package com.raywenderlich.android.imet.data.db {
      class PeopleDao_Impl {
      }
    }
  }
  

  package com.raywenderlich.android.imet {
    package com.raywenderlich.android.imet.data.db {
      class PeopleDatabase_Impl {
      }
    }
  }
  

  package android.arch.core {
    class R {
    }
  }
  

  package android.support.v7.appcompat {
    class R {
    }
  }
  

  package androidx.navigation {
    package androidx.navigation.fragment {
      package androidx.navigation.fragment.ktx {
        class R {
        }
      }
    }
  }
  

  package androidx.navigation {
    package androidx.navigation.fragment {
      class R {
      }
    }
  }
  

  package android.support.fragment {
    class R {
    }
  }
  

  package android.arch.lifecycle {
    package android.arch.lifecycle.extensions {
      class R {
      }
    }
  }
  

  package android.support.coreutils {
    class R {
    }
  }
  

  package androidx.navigation {
    package androidx.navigation.common {
      class R {
      }
    }
  }
  

  package android.support.transition {
    class R {
    }
  }
  

  package android.arch.lifecycle {
    package android.arch.lifecycle.viewmodel {
      class R {
      }
    }
  }
  

  package androidx.navigation {
    package androidx.navigation.ui {
      class R {
      }
    }
  }
  

  package android.support.v4 {
    class R {
    }
  }
  

  package android.support.graphics.drawable {
    package android.support.graphics.drawable.animated {
      class R {
      }
    }
  }
  

  package android.support.mediacompat {
    class R {
    }
  }
  

  package android.support.design {
    class R {
    }
  }
  

  package androidx.navigation {
    class R {
    }
  }
  

  package androidx.navigation {
    package androidx.navigation.ktx {
      class R {
      }
    }
  }
  

  package com.raywenderlich.android.imet {
    class R {
    }
  }
  

  package android.arch.persistence.db {
    package android.arch.persistence.db.framework {
      class R {
      }
    }
  }
  

  package android.arch.lifecycle {
    package android.arch.lifecycle.livedata {
      package android.arch.lifecycle.livedata.core {
        class R {
        }
      }
    }
  }
  

  package android.support.compat {
    class R {
    }
  }
  

  package android.support.v7.recyclerview {
    class R {
    }
  }
  

  package android.arch.lifecycle {
    package android.arch.lifecycle.livedata {
      class R {
      }
    }
  }
  

  package android.arch.persistence.db {
    class R {
    }
  }
  

  package androidx.navigation {
    package androidx.navigation.ui {
      package androidx.navigation.ui.ktx {
        class R {
        }
      }
    }
  }
  

  package android.support.coreui {
    class R {
    }
  }
  

  package android.support.constraint {
    class R {
    }
  }
  

  package android.support.v7.cardview {
    class R {
    }
  }
  

  package android.support.graphics.drawable {
    class R {
    }
  }
  

  package android.arch.persistence.room {
    class R {
    }
  }
  

  package android.arch.lifecycle {
    class R {
    }
  }
  

  PeopleDao_Impl -up-|> PeopleDao
  PeopleDatabase_Impl -up-|> PeopleDatabase


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
